catalog/urls.py
from django.urls import path
from . import views

urlpatterns = [
	path('', views.index, name='index'),
    path('books/', views.BookListView.as_view(), name='books'),
    path('book/<int:pk>', views.BookDetailView.as_view(), name='book-detail')
]

terminus/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.views.generic import RedirectView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('catalog/', include('catalog.urls')),
    path('', RedirectView.as_view(url='catalog/')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

catalog/models.py
from django.db import models
from django.urls import reverse
import uuid

# Create your models here.
class Genre(models.Model):
	""" Model representing a book genre"""
	name = models.CharField(max_length=200, help_text="Enter a book genre (e.g. Science Fiction")

	def __str__(self):
		"""String for representing the Model object"""
		return self.name

class Language(models.Model):
	"""Model representing a book's language"""

	language = models.CharField(max_length=200, help_text="Enter a book's language")

	def __str__(self):
		return self.language

class Book(models.Model):
	"""Model representing a book (but not a specific copy of a book)"""
	title = models.CharField(max_length=200)

	# Foreign Key used because book can only have one author, but authors can have multiple books
	# Author as a string rather than object because it has not been declared yet
	author = models.ForeignKey('Author', on_delete=models.SET_NULL, null=True)

	summary = models.TextField(max_length=1000, help_text="Enter brief description of the book")
	isbn = models.CharField("ISBN", max_length=13, unique=True, help_text='13 Character <a href="https://www.isbn-international.org/content/what-isbn">ISBN number</a>')

	# ManyToManyField used because genre can contain many books. Books can cover many genres.
	# Genre class has already been defined, so we can specify the object above
	genre = models.ManyToManyField(Genre, help_text="Select a genre for this book")

	language = models.ForeignKey(Language, on_delete=models.SET_NULL, null=True)

	def __str__(self):
		"""String for representing the Model object"""
		return self.title

	def get_absolute_url(self):
		"""Returns the URL to access a detail record for this book
        Note that the 'book-detail' name is the name asigned to a URL in
        catalog/urls.py as an argument to `path()`
        """
		return reverse('book-detail', args=[str(self.id)])

	def display_genre(self):
		"""Create a string for the Genre, used to display genre in Admin"""
		return ', '.join(genre.name for genre in self.genre.all()[:3])

	display_genre.short_description = "Genre"

class BookInstance(models.Model):
	"""Model representing a specific copy of a book"""
	# UUIDField is used for the id field to set it as the primary_key for this model. This type of field allocates a globally unique value for each instance (one for every book you can find in the library).
	id = models.UUIDField(primary_key=True, default=uuid.uuid4,
	help_text="Unique ID for this particular book")
	book = models.ForeignKey("Book", on_delete=models.RESTRICT, null=True)
	imprint = models.CharField(max_length=200)
	due_back = models.DateField(null=True, blank=True)

	LOAN_STATUS = (
		("m", "Maintenance"),
		("o", "On Loan"),
		("a", "Available"),
		("r", "Reserved")
	)

	status = models.CharField(max_length=1,
							  choices=LOAN_STATUS,
							  blank=True,
							  default="m",
							  help_text="Book availability"
	)

	class Meta:
		ordering = ['due_back']

	def __str__(self):
		return f"{self.id} ({self.book.title})"


class Author(models.Model):
	"""Model representing an author"""
	fname = models.CharField(max_length=100)
	sname = models.CharField(max_length=100)
	date_of_birth = models.DateField(null=True, blank=True)
	date_of_death = models.DateField("Died", null=True, blank=True)

	class Meta:
		ordering = ['sname', 'fname']

	def get_absolute_url(self):
		"""Returns URL to access a particular author instance"""
		return reverse('author-detail', args=[str(self.id)])

	def __str__(self):
		return f"{self.sname}, {self.fname}"

catalog/views.py
from django.shortcuts import render
from django.views import generic
from .models import Book, Author, BookInstance, Genre

# Create your views here.

def index(request):
	"""View function for home page of the site"""

	# Generate counts of some of the name objects
	num_books = Book.objects.all().count()
	num_instances = BookInstance.objects.all().count()

	# Available books (with status = 'a')
	num_instances_available = BookInstance.objects.filter(status__exact='a').count()

	# Another option for counting. `all()` is implied by default
	num_authors = Author.objects.count()

	num_scifi = Book.objects.filter(genre__name__icontains="sci-fi").count()
	context = {
		'num_books':num_books,
		'num_instances':num_instances,
		'num_instances_available':num_instances_available,
		'num_authors':num_authors,
		'num_scifi':num_scifi
	}

	# Render HTML template index.html and pass data from the context variable
	return render(request, 'index.html', context=context)

class BookListView(generic.ListView):
    model = Book
    #context_object_name = 'my_book_list'   # your own name for the list as a template variable
    #queryset = Book.objects.filter(title__icontains='war')[:5] # Get 5 books containing the title war
    template_name = 'books/my_arbitrary_template_name_list.html'  # Specify your own template name/location

class BookDetailView(generic.DetailView):
    model = Book

catalog/templates/catalog/book_detail.html
{% extends "layout.html" %}

{% block title %}
{{ book.title }}
{% endblock %}

{% block content %}
  <h1>Title: {{ book.title }}</h1>

  <p><strong>Author:</strong> <a href="">{{ book.author }}</a></p> <!-- author detail link not yet defined -->
  <p><strong>Summary:</strong> {{ book.summary }}</p>
  <p><strong>ISBN:</strong> {{ book.isbn }}</p>
  <p><strong>Language:</strong> {{ book.language }}</p>
  <p><strong>Genre:</strong> {{ book.genre.all|join:", " }}</p>

  <div style="margin-left:20px;margin-top:20px">
    <h4>Copies</h4>

    {% for copy in book.bookinstance_set.all %}
      <hr>
      <p class="{% if copy.status == 'a' %}text-success{% elif copy.status == 'm' %}text-danger{% else %}text-warning{% endif %}">
        {{ copy.get_status_display }}
      </p>
      {% if copy.status != 'a' %}
        <p><strong>Due to be returned:</strong> {{ copy.due_back }}</p>
      {% endif %}
      <p><strong>Imprint:</strong> {{ copy.imprint }}</p>
      <p class="text-muted"><strong>Id:</strong> {{ copy.id }}</p>
    {% endfor %}
  </div>
{% endblock %}

catalog/templates/catalog/book_list.html
{% extends "layout.html" %}

{% block title %}
Books
{% endblock %}

{% block content %}
	<h1>Book List</h1>
	{% if book_list %}
	<ul>
		{% for book in object_list %}
			<li>
				<a href="{{ book.get_absolute_url }}">{{ book.title }}</a> ({{ book.author }})
			</li>
		{% endfor %}
	</ul>
	{% else %}
		<p>There are no books in the library</p>
	{% endif %}
{% endblock %}

catalog/templates/index.html
{% extends "layout.html" %}

{% block title %}
Terminus Catalog
{% endblock %}

{% block content %}
  <h1>Terminus Home</h1>
  <p>Welcome to Terminus!</p>
  <h2>Dynamic content</h2>
  <p>The library has the following record counts:</p>
  <ul>
    <li><strong>Books:</strong> {{ num_books }}</li>
    <li><strong>Copies:</strong> {{ num_instances }}</li>
    <li><strong>Copies available:</strong> {{ num_instances_available }}</li>
    <li><strong>Authors:</strong> {{ num_authors }}</li>
    <li><strong>Sci-Fi:</strong> {{ num_scifi }}</li>
  </ul>
{% endblock %}

catalog/templates/layout.html
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
	{% load static %}
	<link rel="stylesheet" href="{% static 'css/styles.css' %}">
	<title>{% block title %}{% endblock %}</title>
</head>
<body>
	<div class="container-fluid">
		<div class="row">
			<div class="col-sm-2">
			{% block sidebar %}
				<ul class="sidebar-nav">
					<li><a href="{% url 'index' %}">Home</a></li>
					<li><a href="{% url 'books' %}">All books</a></li>
					<li><a href="">All authors</a></li>
				</ul>
			{% endblock %}
			</div>
		<div class="col-sm-10">{% block content %}{% endblock %}</div>
		</div>
	</div>
</body>
</html>